#!/usr/bin/python3
import sys
da = []
for i in sys.stdin:
	da.append([int(j) for j in i.split()])
z = 0
z2 = 0

def issafe(i):
	x,y = (1,3) if i[1]>i[0] else (-3,-1)
	for j in range(1,len(i)):
		if not(i[j]-y<=i[j-1] and i[j-1]<=i[j]-x):
			return False
	return True
	
for i in da:
	if issafe(i):
		z += 1
		z2 += 1
	else:
		for j in range(len(i)):
			a = i.copy()
			a.pop(j)
			if issafe(a):
				z2 += 1
				break
print(z)
print(z2)
