#!/usr/bin/python3
import sys
import time

tm = time.perf_counter()
z = 0
z2 = 0
for i in sys.stdin:
	[a,b] = i.split(': ')
	b = [int(x) for x in b.split()]
	a = int(a)
	c = b[0]
	b = b[1:]
	for i in range(2**len(b)):
		x = c
		for j in b:
			match i&1:
				case 0:
					x = x+j
				case 1:
					x = x*j
			i = i//2
		if x==a:
			z += a
			break
	for i in range(3**len(b)):
		x = c
		for j in b:
			match i%3:
				case 0:
					x = x+j
				case 1:
					x = x*j
				case 2:
					x = str(x)+str(j)
					if len(x)>15:
						break
					x = int(x)
			i = i//3
		if x==a:
			z2 += a
			break
print('({:0.1f} sec)'.format(time.perf_counter()-tm))
print(z)
print(z2)
